{%set name = "jira" %}
{%set version = "1.0.14" %}
{%set hash_type = "sha256" %}
{%set hash_val = "a35e270c37c7f43f12bb67e4cad226e81f6bf926acfc35d4b60fc88715cbccf6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  entry_points:
    - jirashell = jira.jirashell:main

  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - pbr >=1.9
    - requests-oauthlib >=0.6.1
    - requests >=2.10.0
    - requests-toolbelt
    - six >=1.10.0
    - setuptools >=20.10.1
    - defusedxml

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/pycontribs/jira
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'The easiest way to automate JIRA'

extra:
  recipe-maintainers:
    - ericdill
    - parente
    - pmlandwehr
