travis:
  secure:
    BINSTAR_TOKEN: Azr4R8HpYK8XrCRXYjabtSEw8Ocis6rJHf4YI10cjXNOLuZoHZI5x0bhq/URjaoIu8jOYo4e41u6PdnCZwvvYAhfmguIXs2uttSswH8ePtkUV1dBQjzID5XmUl/0r8CuWXHQYTyMBVT0obMu6D/44iQneyp1NTS+s+KMFmRt7a7wThT4bGj3M/gmC4mp+sY2XiRtPkl0mBhACLecxUd3m6/JsPOMYgjTbGY4btrCVk2SSyLGmDRvY45Gxa22M3z8ZuUV98pvH3FCLaEiItbG+x09eJi71ii0Ts8f0eoThPBX0fAeVC0V2yzpNFqYVCRMVkPmoz23NSMcdLoRiYBUwbM5L7zAVilSxOdmvoZTYous1YcHLK3cpGdarSluZE7OQFW9BCedSoWUy/WWv2WeCw1IeCeReLbP9h8tfxBqq+u4upwTDwA6V7lB/zeFlEIyKzA3bJxWTd3o5H3wQswhtHRBOWdRLT+IgK39sZHxU3L9pmjRKQIegQGaxf1KxPyFu6azTXKO+fBrb/8tC2qdOUPs1yw0DPN1cbsGaAKLcV0MWdSfN5bOBxPsr+7+HEmhKfIZTWka8IyqNciZcdEfzbc0vZxp6pybxI1Zfr+YDvAphvxI9u3N+SZsi6Jvn0BeW9aiKK2zrcYTWnQ4WfVI3BHbJgzgG5OOTlNpnz6PYS0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
