travis:
  secure:
    BINSTAR_TOKEN: Hl0tPd5zEmvxdHnKgmeHgmWS0aHlRvG+TtH/y/Z5y4tGQNpkHz3XLnZoDkx1wN/fI/4eUL1OFcxKKqFb4ZwkVh8qNu9fck3qkTr3KM9pI4eB8wCi+veLAMmyj0kWO7zuxrHeRFn7n3Gn8tQIm0rdkYkTUDXL8S3JPrVCVtHfwRnFUUne0WzNYlPprMST/MM53hYqNB2laI3sp5VFUAohWePwhWCcBs5sC4T2xzqJiRePAR02FxumEDCiNzD8k1SwGORTyvmOlb1yzCLjZ1OfD85b7kQ7ddvwsBsz9JlS20Il0acVB5auav2/ZKboHLJ8sFs0opaZS55rfplhnc8mfpppT4pPL0PtqwKL9PzH6kC+OQl/xdGWC57x5mKDOKgdeJ5956fjdKuwdvvUnmMamUEpXoChOZ+Pz9UmshWCoRu6w+EI3aj5rpvsA33EW07mEiVpp/RAUdEXGedTvyvtZENLISXndyBXENcj1d9LxKwgjwiXeT2YFFq9mr1Iqg6rm6ipPOXqvjuiaGkWeQ2SYUaY963YMCmQvspvVFU9XCpJGkAnXsYXKdVi/cpnymhbwTyKt3tKgXQnMz+0FflejWa6ImFTq4Exv8BTyKcOA3cZtcXxK6wMPXp6G/bCSCFK/h5hDK8DHyQQDXN/AFwiN6oKcUOcuhjFiV5uAUbVoJQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
